USE [SoS_Build]
GO

/****** Object:  Table [dbo].[luCities]    Script Date: 2/20/2018 2:15:56 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[luCities](
	[CityID] [int] IDENTITY NOT NULL,
	[CityName] [nvarchar](30) NOT NULL,
 CONSTRAINT [PK_luCities] PRIMARY KEY CLUSTERED 
(
	[CityID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


