USE [BootCamp1]
GO

/****** Object:  Table [dbo].[datTrays]    Script Date: 3/12/2018 3:29:13 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[datTrays](
	[TrayID] [int] NOT NULL,
	[WorkstationID] [int] NOT NULL,
 CONSTRAINT [PK_datTrays] PRIMARY KEY CLUSTERED 
(
	[TrayID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

