USE [SoS_Build]
GO

/****** Object:  Table [dbo].[datTrays]    Script Date: 3/25/2018 8:58:40 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[datTrays](
	[TrayID] [int] IDENTITY(1,1) NOT NULL,
	[WorkStationID] [int] NOT NULL,
 CONSTRAINT [PK_datTrays] PRIMARY KEY CLUSTERED 
(
	[TrayID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

