USE [SoS_Build]
GO

/****** Object:  Table [dbo].[luPhoneTypes]    Script Date: 3/25/2018 9:02:58 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[luPhoneTypes](
	[PhoneTypeID] [tinyint] IDENTITY(1,1) NOT NULL,
	[PhoneType] [nvarchar](10) NOT NULL,
 CONSTRAINT [PK_luPhoneTypes] PRIMARY KEY CLUSTERED 
(
	[PhoneTypeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

